version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/control-gastos
      - JWT_SECRET=secreto_super_seguro123
      - PORT=3001
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:3001/api
    depends_on:
      - backend

volumes:
  mongo_data:
